import Head from 'next/head'
import Image from 'next/image'
import { Title } from '../components/Title'
import styles from '../styles/Home.module.scss'
import React from 'react';
import Menu from '../components/Menu'

export default function Home() {

  return (
    <div className={styles.container}>
      <Head>
        <title>LimeSharp Tasks</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Title pageTitle={'Limesharp test'} />
        <Menu />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://marcio.vercel.app/"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by Márcio Iwamoto
        </a>
      </footer>
    </div>
  )
}
